/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, OrbitControls } from '@react-three/drei/';

export default function TRX2({ toneMapped = true, ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/TRX2RX.glb');
	return (
		<>
			<OrbitControls />
			<group ref={group} {...props} dispose={null}>
				<group position={[0, 0.91, 0]} scale={[1.07, 0.96, 0.3]}>
					<mesh material={materials['Material.001']} geometry={nodes.Cube.geometry} />
					<mesh material={materials.Material} geometry={nodes.Cube_1.geometry} />
					<mesh material={materials['CC0Textures/Metal029/1K-JPG']} geometry={nodes.Cube_2.geometry} />
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant.geometry}
						position={[-0.96, -0.3, -0.71]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant1.geometry}
						position={[-0.96, 0.2, -0.18]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant2.geometry}
						position={[-0.96, 0.84, -0.7]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant3.geometry}
						position={[-0.96, 0.3, -0.71]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant4.geometry}
						position={[-0.96, -0.87, -0.72]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant5.geometry}
						position={[-0.96, -0.2, -0.18]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.ant6.geometry}
						position={[-0.96, 0, -0.16]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
					<mesh
						material={materials['CC0Textures/Metal034/1K-JPG']}
						geometry={nodes.antgps.geometry}
						position={[-0.96, 0, -0.78]}
						rotation={[0, 0, Math.PI / 2]}
						scale={[0.02, 0.01, 0.06]}
					/>
				</group>
			</group>
		</>
	);
}

useGLTF.preload('/TRX2RX.glb');
